"""Prints the data-quality report for the seed dataset as Markdown tables:
one row per tariff schedule and per incentive scheme version, with its
jurisdiction, effective period, source and verification status, plus every
validation problem found.

Reads only the JSON files in backend/app/data/ (no database). Exits with a
non-zero status if any problem is found, so it can gate a deploy.

Run from backend/ with:

    python -m scripts.data_quality_report [--write PATH]
"""

import argparse
import sys
from datetime import date
from pathlib import Path

from app.data_validation import dataset


def _period(start: date, end: date | None) -> str:
    return f"{start} to {end or 'until further orders'}"


def _rates(record) -> str:
    slabs = record.slabs
    energy = ", ".join(f"{s.energy_charge_inr_per_kwh:.2f}" for s in slabs)
    return f"{len(slabs)} slab(s): Rs/kWh {energy}"


def build_report() -> tuple[str, list[str]]:
    tariffs = dataset.load_tariff_schedules()
    incentives = dataset.load_incentive_records()
    discoms = dataset.load_discom_records()

    problems = (
        dataset.check_discom_dataset(discoms)
        + dataset.check_tariff_dataset(tariffs, dataset.known_discom_keys(discoms))
        + dataset.check_incentive_dataset(incentives)
    )

    lines = [
        "# Automated data-quality report",
        "",
        "Generated by `python -m scripts.data_quality_report` from the JSON files in `backend/app/data/`. "
        "Do not edit by hand.",
        "",
        f"- Tariff schedules: **{len(tariffs)}**  |  Incentive scheme versions: **{len(incentives)}**  |  "
        f"DISCOMs: **{len(discoms)}**",
        f"- Validation problems: **{len(problems)}**",
        "",
        "## Tariffs",
        "",
        "| State/UT | DISCOM | Category | Version | Effective | Rates | Source | Order | Page | Verified |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for _, t in tariffs:
        lines.append(
            f"| {t.state or t.union_territory} | {t.discom_short_code or 'state-level'} | "
            f"{t.consumer_category.value} | `{t.tariff_version}` | {_period(t.effective_from, t.effective_to)} | "
            f"{_rates(t)} | {t.source.name} | {t.source.order_number} | {t.source.page} | "
            f"{t.verification_status.value} ({t.source.last_verified}) |"
        )

    lines += [
        "",
        "## Incentives",
        "",
        "| Programme | Level | State/UT | DISCOM | Technology | Category | Version | Effective | Amount/formula | "
        "Source | Order | Verified |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for _, i in incentives:
        slabs = (i.calculation_rules or {}).get("slabs")
        formula = (
            "; ".join(
                f"{s['capacity_min_kw']}-{s['capacity_max_kw']} kW @ Rs {s['rate_inr_per_kw']}/kW" for s in slabs
            )
            if slabs
            else i.subsidy_type.value
        )
        scope = i.state or i.union_territory or "regional variants via eligibility_rules"
        lines.append(
            f"| {i.scheme_name} | {i.level.value} | {scope} | {i.discom_short_code or '-'} | "
            f"{i.technology.value} | {i.consumer_category.value if i.consumer_category else 'any'} | "
            f"`{i.scheme_version}` | {_period(i.effective_from, i.effective_to)} | {formula} | "
            f"{i.source.name} | {i.source.order_number} | {i.verification_status.value} ({i.source.last_verified}) |"
        )

    lines += ["", "## DISCOM registry", "", "| Short code | Name | State/UT | Source document |", "|---|---|---|---|"]
    for _, d in discoms:
        lines.append(f"| {d.short_code} | {d.name} | {d.state or d.union_territory} | {d.source.document} |")

    lines += ["", "## Problems", ""]
    lines += [f"- {p}" for p in problems] or ["None."]
    return "\n".join(lines) + "\n", problems


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", metavar="PATH", help="Also write the report to this file.")
    args = parser.parse_args()

    report, found = build_report()
    print(report)
    if args.write:
        Path(args.write).write_text(report, encoding="utf-8")
    sys.exit(1 if found else 0)
