"""india discom tariff and incentive architecture

Revision ID: 4a3fd3105658
Revises: 2bfbbba30d20
Create Date: 2026-09-16 20:22:40.100659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum

# The generic sa.Enum(..., create_type=False) does not reliably suppress
# CREATE TYPE on the postgresql dialect — the dialect-specific ENUM does.
BUILDING_TYPE_ENUM = PGEnum(
    'HOME', 'SCHOOL', 'COLLEGE', 'OFFICE', 'SHOP', 'SMALL_INSTITUTION', 'OTHER',
    name='buildingtype', create_type=False,
)


# revision identifiers, used by Alembic.
revision: str = '4a3fd3105658'
down_revision: Union[str, Sequence[str], None] = '2bfbbba30d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate does not detect added enum labels — added by hand.
    # Safe within this transaction since PG 12+: the restriction is only on
    # using the new value in the same transaction it was added in, and
    # nothing here inserts a 'college' row.
    # NOTE: Postgres enum labels here are the Python enum member *names*
    # (e.g. 'HOME' for BuildingType.HOME, whose .value is "home") — SQLAlchemy's
    # default Enum binds/reads by member name, not value. Must be 'COLLEGE',
    # not 'college', to match that convention.
    op.execute("ALTER TYPE buildingtype ADD VALUE IF NOT EXISTS 'COLLEGE'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discoms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('union_territory', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electricity_tariffs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('union_territory', sa.String(length=120), nullable=True),
    sa.Column('discom_id', sa.Uuid(), nullable=True),
    sa.Column('consumer_category', BUILDING_TYPE_ENUM, nullable=False),
    sa.Column('tariff_name', sa.String(length=255), nullable=False),
    sa.Column('slab_min_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('slab_max_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('energy_charge_inr_per_kwh', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('fixed_charge_inr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('demand_charge_inr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discom_id'], ['discoms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incentive_programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Enum('CENTRAL', 'STATE', 'DISCOM', name='incentivelevel'), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('union_territory', sa.String(length=120), nullable=True),
    sa.Column('discom_id', sa.Uuid(), nullable=True),
    sa.Column('consumer_category', BUILDING_TYPE_ENUM, nullable=True),
    sa.Column('technology', sa.Enum('SOLAR', 'WIND', 'HYBRID', 'BATTERY', 'OTHER', name='renewabletechnology'), nullable=False),
    sa.Column('min_system_size_kw', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_system_size_kw', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('subsidy_type', sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', 'PER_KW', 'OTHER', name='subsidytype'), nullable=False),
    sa.Column('subsidy_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentage_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('maximum_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('eligibility_rules', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discom_id'], ['discoms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incentive_programs')
    op.drop_table('electricity_tariffs')
    op.drop_table('discoms')
    # ### end Alembic commands ###

    # Autogenerate does not drop the Postgres enum types created for the
    # columns above (see the fix for the same issue in the Phase 2
    # migration) — without this, re-running upgrade() after a downgrade
    # fails with "type already exists".
    sa.Enum(name='incentivelevel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='renewabletechnology').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='subsidytype').drop(op.get_bind(), checkfirst=True)

    # Postgres has no "ALTER TYPE ... DROP VALUE" — removing 'college' from
    # buildingtype would require rebuilding the type (create new type,
    # migrate every column using it, drop the old type) and is not
    # supported by this downgrade. This migration's enum change is
    # intentionally one-way; the table drops above still fully reverse.
