"""phase 2 assessment tables

Revision ID: fcab86db3e7d
Revises: 
Create Date: 2026-09-16 19:19:46.280074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcab86db3e7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buildings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('building_type', sa.Enum('HOME', 'SCHOOL', 'OFFICE', 'SHOP', 'SMALL_INSTITUTION', 'OTHER', name='buildingtype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'COMPLETED', name='assessmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_constraints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('roof_area_sqft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('land_area_sqft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_inr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('backup_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_table('energy_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('monthly_consumption_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('annual_consumption_kwh', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('formatted_address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    op.drop_table('energy_profiles')
    op.drop_table('building_constraints')
    op.drop_table('assessments')
    op.drop_table('buildings')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Autogenerate does not drop the Postgres enum types created for the
    # buildings/assessments columns above — without this, re-running
    # upgrade() after a downgrade fails with "type already exists".
    sa.Enum(name='buildingtype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='assessmentstatus').drop(op.get_bind(), checkfirst=True)
